dist:
  name: otelcol-dev
  description: Otelcol distribution to develop fluentforward exporters
  output_path: ./otelcol-dev
  otelcol_version: 0.89.0

exporters:
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.89.0

receivers:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/journaldreceiver v0.89.0